1749045710.1934328 | Node Node9944 | [BOOT] | Starting Orbit Node for ORB.B77AC60F52529B834E4DAF21 (Node9944)
1749045710.2441902 | Node Node9944 | [DISCOVERY] | Added new peer: Node5786
1749045710.2569385 | Node Node9944 | [DISCOVERY] | Added new peer: Node7863
1749045727.8217862 | Node Node5516 | [BOOT] | Starting Orbit Node for system (Node5516)
1749045727.9798207 | Node Node5516 | [DISCOVERY] | Added new peer: Node5786
1749045727.9806497 | Node Node5516 | [DISCOVERY] | Added new peer: Node7863
1749045727.981287 | Node Node5516 | [DISCOVERY] | Added new peer: Node9944
1749045730.3021822 | Node Node9944 | [DISCOVERY] | Added new peer: Node5516
1749051990.4936614 | Node Node9944 | [INFO] | Validating Block.
1749055016.2095373 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749055017.3620486 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c630b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749058763.5944252 | Node Node9944 | [INFO] | Validating Block.
1749058886.1129932 | Node Node9944 | [INFO] | Validating Block.
1749059313.2391748 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfd70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059315.1107738 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059318.1490662 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2810>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059325.1224077 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05310>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059325.90237 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5340>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059328.158529 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5280>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059335.1293962 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c630b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059338.166579 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059343.2433524 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62570>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059345.1379044 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dff920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059348.1723762 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4560>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059355.1433253 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce79a7dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059425.2667189 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059428.299364 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059433.525499 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce700b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059435.274317 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059438.305338 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04080>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059445.2797134 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059446.0364938 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3c440>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059448.3131745 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3d460>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059455.2853632 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059458.3189182 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059463.5325153 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf050>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059465.2946668 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059468.3266406 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059475.3007047 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059476.044449 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5400>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059478.3367183 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c381ebdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059485.3166666 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05280>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060296.9325402 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060299.7991126 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5310>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060304.9914021 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060306.9403582 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060309.8063328 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d046e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060316.9475594 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060317.3961241 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060319.8127196 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a3b7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060326.954459 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04680>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060329.8207288 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d445f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060334.998203 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060336.959601 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060339.826235 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060377.0142012 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4140>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060377.4578276 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060379.8844974 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca28d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060387.0225325 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060389.8914664 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38378740>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060395.0513337 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060397.029015 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060399.8992684 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060407.0314023 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca42c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060407.4612682 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de1a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060409.906753 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d079e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060417.0386112 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfcb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060419.9128842 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d043e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060425.0616908 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060427.0483067 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d068d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060429.92123 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d461b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060437.0575616 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfa40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060437.4677477 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060439.9316332 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07680>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060447.0635993 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca42c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060449.941769 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060455.0654783 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060457.0723941 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04080>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060459.948443 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060467.082461 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d071a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060467.4764926 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46a80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060469.9557767 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3800>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060477.088042 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060479.9633832 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060485.0706124 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060487.0956352 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd910>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060489.9715543 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04470>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060497.104293 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d057c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060497.4819977 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46270>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060499.9749827 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060507.1110783 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060509.9771526 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060515.0758123 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060517.1162515 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca42c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060519.9825535 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a049e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060527.1240451 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060527.4862323 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2900>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060529.9903886 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060537.1340215 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47583b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060539.996645 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060545.0847006 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060547.1361506 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce82e50a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060550.004253 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060557.1429555 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060557.4944963 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d043e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060560.0148146 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d06ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060567.1474876 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060570.021861 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46630>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060575.090223 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060577.1535947 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf440>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060580.029897 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060587.1609416 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce71ca9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060587.5019784 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04500>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060590.039496 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060597.170438 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060600.045936 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3290>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060605.1004844 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060607.1770298 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759670>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060610.056362 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060617.1817842 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060617.5055263 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060620.062576 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060627.1885772 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce700b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060630.0660436 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060635.1080778 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccee10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060637.1976655 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759250>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060640.0712008 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060647.2013109 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060647.508249 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb5880>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060650.0773818 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060657.207932 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce7a93c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060660.0850163 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d05cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060717.3145566 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca7590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060720.187692 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5340>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060725.2123344 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c625d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060727.3227146 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a060>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060730.1954799 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060737.3271394 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060737.634375 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb61b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060740.2027931 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c392b5190>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060747.333117 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060790.288301 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2840>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060797.4157684 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dded80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060797.7031314 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46630>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060800.296077 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060807.4235141 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a060>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060810.301786 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060815.3501835 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060817.4313705 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfe90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060820.3123975 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060827.4404168 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dfeb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060827.7116196 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38aa9430>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060830.320531 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c393250a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060837.446634 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c624e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060840.3282301 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060845.3566983 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a990>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060847.4580271 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475bb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060850.334311 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060857.4663606 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060857.7205305 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce41a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060860.3416188 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e1a9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060867.4732037 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060870.349559 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060875.3635437 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfa70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060877.4812086 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060880.3562171 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060887.4880824 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060887.7262342 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46930>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060890.3641326 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2000>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060897.494254 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62720>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060900.3668618 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e96840>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060905.370513 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060907.499393 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce700b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060910.3743641 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060917.5069215 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060917.7331553 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060920.3804948 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060927.5131037 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060930.3834066 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060935.375934 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060937.521953 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060940.3904338 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060947.5311644 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060947.7405524 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060950.3954651 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47470>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060957.5378692 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d06480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060960.4018447 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46600>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060965.385036 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060967.545756 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060970.410126 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060990.0281534 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62d80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060990.2104201 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a7d7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061001.9660661 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061064.099352 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05820>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061066.9525948 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d477d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061071.9205701 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061074.1058903 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061076.9566772 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45820>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061084.1125677 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c619d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061084.2843645 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a7d7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061086.965221 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca1c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061094.116988 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfe00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061117.000822 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061124.1648912 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05400>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061127.0084171 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061131.9824934 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfd40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061134.1729558 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061137.0147517 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061144.181944 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c639e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061144.3490274 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3140>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061147.0251815 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de1a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061154.1910124 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce711d370>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061157.0341032 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce7950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061161.9885824 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b140>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061164.196309 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce77b7bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061167.0410998 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d471d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061174.2041063 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c610a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061174.357037 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3fc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061177.0492966 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d455b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
