1749045710.1934328 | Node Node9944 | [BOOT] | Starting Orbit Node for ORB.B77AC60F52529B834E4DAF21 (Node9944)
1749045710.2441902 | Node Node9944 | [DISCOVERY] | Added new peer: Node5786
1749045710.2569385 | Node Node9944 | [DISCOVERY] | Added new peer: Node7863
1749045727.8217862 | Node Node5516 | [BOOT] | Starting Orbit Node for system (Node5516)
1749045727.9798207 | Node Node5516 | [DISCOVERY] | Added new peer: Node5786
1749045727.9806497 | Node Node5516 | [DISCOVERY] | Added new peer: Node7863
1749045727.981287 | Node Node5516 | [DISCOVERY] | Added new peer: Node9944
1749045730.3021822 | Node Node9944 | [DISCOVERY] | Added new peer: Node5516
1749051990.4936614 | Node Node9944 | [INFO] | Validating Block.
1749055016.2095373 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749055017.3620486 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c630b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749058763.5944252 | Node Node9944 | [INFO] | Validating Block.
1749058886.1129932 | Node Node9944 | [INFO] | Validating Block.
1749059313.2391748 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfd70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059315.1107738 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059318.1490662 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2810>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059325.1224077 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05310>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059325.90237 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5340>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059328.158529 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5280>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059335.1293962 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c630b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059338.166579 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059343.2433524 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62570>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059345.1379044 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dff920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059348.1723762 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4560>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059355.1433253 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce79a7dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059425.2667189 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059428.299364 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059433.525499 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce700b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059435.274317 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059438.305338 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04080>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059445.2797134 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059446.0364938 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3c440>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059448.3131745 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3d460>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059455.2853632 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059458.3189182 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059463.5325153 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf050>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059465.2946668 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059468.3266406 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059475.3007047 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059476.044449 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5400>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059478.3367183 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c381ebdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749059485.3166666 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05280>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060296.9325402 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060299.7991126 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5310>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060304.9914021 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060306.9403582 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060309.8063328 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d046e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060316.9475594 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060317.3961241 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060319.8127196 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a3b7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060326.954459 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04680>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060329.8207288 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d445f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060334.998203 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060336.959601 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060339.826235 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060377.0142012 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4140>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060377.4578276 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060379.8844974 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca28d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060387.0225325 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060389.8914664 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38378740>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060395.0513337 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060397.029015 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060399.8992684 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060407.0314023 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca42c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060407.4612682 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de1a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060409.906753 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d079e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060417.0386112 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfcb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060419.9128842 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d043e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060425.0616908 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060427.0483067 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d068d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060429.92123 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d461b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060437.0575616 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfa40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060437.4677477 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060439.9316332 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07680>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060447.0635993 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca42c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060449.941769 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060455.0654783 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060457.0723941 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04080>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060459.948443 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060467.082461 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d071a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060467.4764926 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46a80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060469.9557767 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3800>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060477.088042 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060479.9633832 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060485.0706124 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060487.0956352 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd910>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060489.9715543 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04470>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060497.104293 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d057c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060497.4819977 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46270>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060499.9749827 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060507.1110783 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060509.9771526 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060515.0758123 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060517.1162515 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca42c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060519.9825535 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a049e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060527.1240451 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060527.4862323 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2900>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060529.9903886 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060537.1340215 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47583b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060539.996645 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060545.0847006 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060547.1361506 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce82e50a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060550.004253 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060557.1429555 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060557.4944963 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d043e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060560.0148146 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d06ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060567.1474876 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060570.021861 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46630>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060575.090223 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060577.1535947 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf440>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060580.029897 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060587.1609416 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce71ca9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060587.5019784 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04500>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060590.039496 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060597.170438 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060600.045936 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3290>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060605.1004844 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060607.1770298 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759670>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060610.056362 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060617.1817842 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060617.5055263 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060620.062576 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060627.1885772 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce700b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060630.0660436 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060635.1080778 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccee10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060637.1976655 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759250>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060640.0712008 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060647.2013109 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060647.508249 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb5880>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060650.0773818 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060657.207932 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce7a93c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060660.0850163 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d05cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060717.3145566 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca7590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060720.187692 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5340>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060725.2123344 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c625d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060727.3227146 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a060>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060730.1954799 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060737.3271394 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060737.634375 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb61b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060740.2027931 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c392b5190>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060747.333117 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060790.288301 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2840>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060797.4157684 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dded80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060797.7031314 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46630>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060800.296077 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060807.4235141 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a060>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060810.301786 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060815.3501835 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060817.4313705 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfe90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060820.3123975 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060827.4404168 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dfeb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060827.7116196 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38aa9430>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060830.320531 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c393250a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060837.446634 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c624e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060840.3282301 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060845.3566983 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a990>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060847.4580271 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475bb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060850.334311 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060857.4663606 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060857.7205305 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce41a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060860.3416188 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e1a9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060867.4732037 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060870.349559 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060875.3635437 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfa70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060877.4812086 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060880.3562171 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060887.4880824 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060887.7262342 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46930>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060890.3641326 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2000>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060897.494254 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62720>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060900.3668618 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e96840>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060905.370513 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060907.499393 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce700b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060910.3743641 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060917.5069215 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060917.7331553 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060920.3804948 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060927.5131037 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060930.3834066 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060935.375934 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060937.521953 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060940.3904338 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060947.5311644 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060947.7405524 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060950.3954651 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47470>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060957.5378692 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d06480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060960.4018447 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46600>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060965.385036 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf920>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060967.545756 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060970.410126 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060990.0281534 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62d80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749060990.2104201 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a7d7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061001.9660661 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061064.099352 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05820>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061066.9525948 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d477d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061071.9205701 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061074.1058903 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce86a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061076.9566772 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45820>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061084.1125677 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c619d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061084.2843645 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38a7d7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061086.965221 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca1c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061094.116988 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfe00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061117.000822 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061124.1648912 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05400>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061127.0084171 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061131.9824934 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfd40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061134.1729558 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061137.0147517 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061144.181944 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c639e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061144.3490274 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3140>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061147.0251815 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de1a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061154.1910124 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce711d370>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061157.0341032 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce7950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061161.9885824 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b140>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061164.196309 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce77b7bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061167.0410998 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d471d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061174.2041063 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c610a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061174.357037 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3fc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749061177.0492966 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d455b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749062730.3245592 | Node Node9944 | [INFO] | Validating Block.
1749063408.3274894 | Node Node9944 | [INFO] | Validating Block.
1749063564.3773563 | Node Node9944 | [INFO] | Validating Block.
1749063781.2267637 | Node Node9944 | [INFO] | Validating Block.
1749063781.4338555 | Node Node9944 | [INFO] | Validating Block.
1749066802.5586839 | Node Node9944 | [INFO] | Validating Block.
1749068261.9318962 | Node Node9944 | [INFO] | Validating Block.
1749068284.5484295 | Node Node9944 | [INFO] | Validating Block.
1749068284.7678654 | Node Node9944 | [INFO] | Validating Block.
1749068581.46169 | Node Node9944 | [INFO] | Validating Block.
1749068581.654193 | Node Node9944 | [INFO] | Validating Block.
1749068930.923411 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069021.0127 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069021.8673909 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069111.126454 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d079b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069112.004623 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069162.0869129 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63860>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069165.422435 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069171.1653051 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069172.0922046 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069175.4319305 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069242.1854126 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069245.5409417 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3020>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069248.2987785 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069252.1909468 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62810>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069255.5508294 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069261.2572756 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c392455b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069262.198698 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069265.5590434 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069272.2067282 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069275.5668716 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d070b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069278.3047702 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069282.2136326 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069285.5764809 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2b40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069291.2679477 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2870>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069292.2222977 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf530>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069295.5838177 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c3835b6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069302.226584 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccff80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069305.5908656 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069308.3173532 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759970>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069312.2368615 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6e36240>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069315.5988698 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca31d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069321.275308 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069322.2419746 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069325.604508 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d044a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069332.2509406 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf560>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069335.6098087 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45670>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069338.325999 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069342.2579021 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d05c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069345.6185646 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d468a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069351.2813318 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069352.2619772 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069355.6257331 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069362.2653775 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63560>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069365.6335251 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c387f9400>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069368.3282733 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069372.2734632 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce82e50a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069375.6413693 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d479e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069381.320364 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d451c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069382.2789552 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069385.6494682 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37f79e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069392.2861953 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c622d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069395.6571295 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069398.3369656 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62990>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069402.2907438 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc110>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069405.6611228 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca28a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069411.3262758 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069412.2982247 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d059d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069415.6653872 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069422.3072515 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf800>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069425.6710463 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069428.3459823 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c610a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069432.313321 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069435.6778946 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069441.3342679 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069442.3187184 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d063f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069445.6831102 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de3170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069452.3274422 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d06f60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069455.6895783 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d06de0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069458.3546834 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069462.3353968 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069465.6966736 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069471.3446395 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47560>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069472.3437724 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf650>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069475.7067728 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d467e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069482.348701 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d06c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069485.7149806 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca30b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749069488.364587 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d07590>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070042.3197553 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce7fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070043.2909737 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070046.7390661 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070053.2945702 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62810>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070056.7468944 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070059.6215823 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070063.3066204 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6e56270>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070066.7603738 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e723f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070072.3246062 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070073.3154004 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d04230>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070076.7683501 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070083.3222458 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63980>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070086.7748735 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d465a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070089.628866 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070093.3264742 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf740>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070096.783424 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070102.3282757 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07320>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070103.3322337 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6d065a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070106.7897189 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3800>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070113.338561 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475acf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070116.7948725 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5070>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070119.63472 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce7a93c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070123.3479216 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf740>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070126.8039248 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070132.3366125 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb6150>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070133.3585985 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63110>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070136.8118 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce69c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070143.3635252 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dddfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070146.8169813 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070149.6454806 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070153.370429 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63980>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070156.8232968 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d05c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070162.3460624 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c381ebdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070163.3777084 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccede0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070166.8296125 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb5070>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070173.3843517 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dfebd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070176.8338664 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37fc7f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070179.6518338 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce82f9760>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070183.3891745 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47585f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070186.8410008 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2c60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070192.3540483 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070193.3985815 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070196.846386 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070203.4096339 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070206.854939 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c391ecbf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070209.660515 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63080>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070213.415963 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070216.8619025 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070222.3639097 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca30b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070223.425161 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c629f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070226.8676975 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070233.4340417 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070236.8757002 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb48c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070239.6684725 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070243.441959 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dfee40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070246.8853953 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070252.3717363 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca1d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070253.4510896 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47949b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070256.8943114 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3290>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070263.4571178 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6f5d280>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070266.8992822 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb5550>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070269.675129 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070273.4631863 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63830>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070276.9075603 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb7110>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070282.3783445 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5520>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070283.4719453 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dddfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070286.9157321 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070293.4855247 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47952e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070296.921528 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070299.6828532 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6f5d280>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070303.4926083 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070306.9281757 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb7170>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070312.3868744 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb5700>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070313.4976928 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475bf20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070316.9343066 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04950>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070323.4997895 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758740>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070326.941533 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070329.7369058 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47590a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070333.506524 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce72849e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070336.949609 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4200>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070342.3946664 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4b60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070343.515091 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c624e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070346.9639657 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb7a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070353.5237985 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47587d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070356.9728508 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07290>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070359.7428517 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c629f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070363.5331316 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63560>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070366.9807193 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070372.4011447 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca1070>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070373.5359788 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47597c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070376.9856153 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d474d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070383.543432 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070386.9912486 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2990>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070389.7527866 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4759d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070393.550826 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63830>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070396.997879 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07680>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070402.4100683 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070403.5583212 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070407.0042512 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5520>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070413.5646172 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475bf80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070417.0107412 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d479b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070419.7608166 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070423.5738997 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070427.0174263 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37de18e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070432.4193017 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07830>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070433.5816543 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62750>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070437.0265954 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca38f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070443.58734 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce79fe240>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070447.0340724 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070449.7697635 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070453.595039 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a810>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070457.0406806 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070462.4218135 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca29f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070463.6007974 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070467.0467546 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070473.6072216 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c639b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070477.0492477 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5520>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070479.7773235 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62540>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070483.6133807 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758380>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070487.0576935 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44530>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070492.4293418 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46480>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070493.6209006 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf440>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070497.0634012 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c393c4d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070522.4360375 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070523.6763732 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758860>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070527.1040788 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070533.6821716 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62750>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070537.1108303 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d47110>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070539.8349128 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62690>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070543.6857033 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dfee40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070547.119599 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4290>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070552.4385104 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070553.6965678 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf530>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070557.1272688 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070563.703674 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce77af8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070567.1320457 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c396939e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070677.2960248 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c391ecbf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070683.8886669 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62720>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070687.3017259 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070690.0202112 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070693.8943932 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce4758050>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070697.3068478 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070702.6125164 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070703.9018233 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478c8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070707.314571 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb7020>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070713.911491 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475be00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070717.3178802 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca31d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070720.02567 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63440>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070723.9156559 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62f00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070727.3226187 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070732.6217656 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c387f7d40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070733.9208896 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070737.3293862 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37f79e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070743.930102 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478d1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070773.9683459 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca7c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070777.3960342 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce51c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070780.09107 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62720>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070783.9750726 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c624e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070787.4039805 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d079b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070792.6700335 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070793.9812639 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070797.409612 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070803.9890254 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478db20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070807.416162 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb4f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070810.0982735 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47580b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070813.995353 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070817.4247165 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070822.6766565 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca34a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070824.0018303 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca7f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070827.4328313 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070834.008607 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070837.4398773 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb55b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070840.1089761 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478e450>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070844.0146072 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca7c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070847.4464183 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb5a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070852.6832802 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce4710>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070854.0198858 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62750>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070857.4529333 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070864.0241203 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a9c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070867.4577308 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2720>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070887.481511 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d049e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070894.0615556 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070897.4875784 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070900.1672275 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070904.0641131 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce71ca990>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070907.4937456 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070912.7378223 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070914.0667076 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce74fef00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070917.4996655 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce5520>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070924.0743964 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce478ed80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070937.5206695 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c34fb63c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070942.747406 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c381a63c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070944.0977705 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070947.527241 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070954.1051507 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccd250>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070957.533696 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070960.2244322 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfe90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070964.1142564 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dddfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070994.1600192 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf830>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749070997.5966358 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3fc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071002.802836 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce50a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071004.1641822 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62e70>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071007.6057997 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071014.1717017 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca7f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071017.6131046 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c39246330>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071020.251495 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6dfee40>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071024.1812727 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475a8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071027.6211774 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d453d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071032.8099344 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c3835b6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071034.1836286 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c61b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071037.6251876 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d07530>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071044.1933115 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c63e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071047.6325357 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3fc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071050.257855 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071054.2003112 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce8294ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071057.6412358 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca2cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071062.8211136 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d45430>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071064.2074208 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccc7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071067.6478229 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37e3efc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071074.212039 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c628a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071092.8283944 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071094.2446578 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ca4350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071097.7141902 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38790b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071104.2497354 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccf290>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071107.7208996 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d46cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071110.3147 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b680>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071114.2566848 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce475b350>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071117.7289531 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c38914800>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071122.8349159 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04410>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071124.2672603 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c62c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071152.8434908 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ce54f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071154.3134882 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccfb00>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071157.7986815 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca3020>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071164.316916 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6c618e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071167.803744 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d44470>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749071170.3899553 | Node Node5516 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce47587d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749072925.9772685 | Node Node9944 | [HEARTBEAT] | Exception: HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /node_ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d044a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749072927.5570557 | Node Node5516 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ce6ccffe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749073101.3610318 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37d04050>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749073513.8730128 | Node Node9944 | [INFO] | Validating Block.
1749073550.0270793 | Node Node9944 | [INFO] | Validating Block.
1749074173.741724 | Node Node9944 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c37ca28d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749077761.9630232 | Node Node1163 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76fae8d220>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749077765.29238 | Node Node12 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73dfdd3260>: Failed to establish a new connection: [Errno 111] Connection refused'))
1749077804.4000752 | Node Node12 | [INFO] | Validating Block.
1749082261.15946 | Node Node12 | [INFO] | Validating Block.
1749084275.533997 | Node Node12 | [INFO] | Validating Block.
1749088375.8533998 | Node Node12 | [INFO] | Validating Block.
1749089766.8664322 | Node Node12 | [INFO] | Validating Block.
1749090814.8860557 | Node Node12 | [INFO] | Validating Block.
1749090983.8268511 | Node Node12 | [INFO] | Validating Block.
1749095039.3046718 | Node Node12 | [INFO] | Validating Block.
1749095065.558557 | Node Node12 | [INFO] | Validating Block.
1749100818.7141254 | Node Node12 | [INFO] | Validating Block.
1749100931.7889042 | Node Node12 | [INFO] | Validating Block.
1749105830.7941518 | Node Node12 | [INFO] | Validating Block.
1749106175.371669 | Node Node12 | [INFO] | Validating Block.
1749106202.189454 | Node Node12 | [INFO] | Validating Block.
1749106202.3548367 | Node Node12 | [INFO] | Validating Block.
1749119950.1024647 | Node Node12 | [INFO] | Validating Block.
1749123927.422428 | Node Node12 | [INFO] | Validating Block.
1749125646.6538126 | Node Node12 | [INFO] | Validating Block.
1749125646.8416862 | Node Node12 | [INFO] | Validating Block.
1749126564.9031975 | Node Node12 | [INFO] | Validating Block.
1749126582.9644506 | Node Node12 | [INFO] | Validating Block.
1749126583.1325111 | Node Node12 | [INFO] | Validating Block.
1749129123.1347165 | Node Node12 | [INFO] | Validating Block.
1749129231.8224778 | Node Node12 | [INFO] | Validating Block.
1749135582.4309993 | Node Node1163 | [DISCOVERY ERROR] | HTTPConnectionPool(host='127.0.0.1', port=7000): Max retries exceeded with url: /active_nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76faf354f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
